// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CTFuncionalidadesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cTFuncionalidades() {
    // Test name: CT_Funcionalidades
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:5173/");
    // 2 | setWindowSize | 1614x881 | 
    driver.manage().window().setSize(new Dimension(1614, 881));
    // 3 | click | css=.rbc-row:nth-child(3) > .rbc-row-segment:nth-child(1) | 
    driver.findElement(By.cssSelector(".rbc-row:nth-child(3) > .rbc-row-segment:nth-child(1)")).click();
    // 4 | click | id=nome | 
    driver.findElement(By.id("nome")).click();
    // 5 | type | id=nome | Teste de Funcionalidade
    driver.findElement(By.id("nome")).sendKeys("Teste de Funcionalidade");
    // 6 | click | id=descricao | 
    driver.findElement(By.id("descricao")).click();
    // 7 | type | id=descricao | Realizando testes de funcionalidade da aplicação
    driver.findElement(By.id("descricao")).sendKeys("Realizando testes de funcionalidade da aplicação");
    // 8 | click | id=horarioInicial | 
    driver.findElement(By.id("horarioInicial")).click();
    // 9 | type | id=horarioInicial | 2024-09-18T09:00
    driver.findElement(By.id("horarioInicial")).sendKeys("2024-09-18T09:00");
    // 10 | click | id=horarioFinal | 
    driver.findElement(By.id("horarioFinal")).click();
    // 11 | type | id=horarioFinal | 2024-09-18T10:00
    driver.findElement(By.id("horarioFinal")).sendKeys("2024-09-18T10:00");
    // 12 | click | id=valor | 
    driver.findElement(By.id("valor")).click();
    // 13 | type | id=valor | 0
    driver.findElement(By.id("valor")).sendKeys("0");
    // 14 | click | id=publicoTotal | 
    driver.findElement(By.id("publicoTotal")).click();
    // 15 | type | id=publicoTotal | 0
    driver.findElement(By.id("publicoTotal")).sendKeys("0");
    // 16 | mouseDown | id=espacoCultural-select-dialog | 
    {
      WebElement element = driver.findElement(By.id("espacoCultural-select-dialog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 17 | mouseUp | css=.MuiBackdrop-invisible | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-invisible"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 18 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 19 | click | css=.MuiMenuItem-root:nth-child(3) | 
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(3)")).click();
    // 20 | mouseDown | id=espaco-select-dialog | 
    {
      WebElement element = driver.findElement(By.id("espaco-select-dialog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 21 | mouseUp | css=.MuiBackdrop-invisible | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBackdrop-invisible"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 22 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 23 | click | css=.MuiMenuItem-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
    // 24 | mouseDown | id=categoria-select-dialog | 
    {
      WebElement element = driver.findElement(By.id("categoria-select-dialog"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 25 | mouseUp | css=.MuiButtonBase-root:nth-child(5) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 26 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 27 | click | css=.MuiButtonBase-root:nth-child(8) > .MuiBox-root | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(8) > .MuiBox-root")).click();
    // 28 | click | css=.MuiButton-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".MuiButton-root:nth-child(2)")).click();
    // 29 | mouseDownAt | css=.css-5pmatr | 341.0104179382324,23.028656005859375
    {
      WebElement element = driver.findElement(By.cssSelector(".css-5pmatr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 30 | mouseMoveAt | css=.css-5pmatr | 341.0104179382324,23.028656005859375
    {
      WebElement element = driver.findElement(By.cssSelector(".css-5pmatr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 31 | mouseUpAt | css=.css-5pmatr | 341.0104179382324,23.028656005859375
    {
      WebElement element = driver.findElement(By.cssSelector(".css-5pmatr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 32 | click | css=.MuiSvgIcon-fontSizeLarge > path:nth-child(1) | 
    driver.findElement(By.cssSelector(".MuiSvgIcon-fontSizeLarge > path:nth-child(1)")).click();
    // 33 | click | css=.MuiGrid-root:nth-child(1) .MuiButtonBase-root:nth-child(2) | 
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) .MuiButtonBase-root:nth-child(2)")).click();
    // 34 | click | css=.MuiTableRow-root:nth-child(25) | 
    driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(25)")).click();
    // 35 | mouseOver | css=.MuiBox-root:nth-child(5) > .MuiButtonBase-root | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiBox-root:nth-child(5) > .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 36 | click | css=.MuiBox-root:nth-child(5) > .MuiButtonBase-root | 
    driver.findElement(By.cssSelector(".MuiBox-root:nth-child(5) > .MuiButtonBase-root")).click();
    // 37 | runScript | window.scrollTo(0,72.5) | 
    js.executeScript("window.scrollTo(0,72.5)");
    // 38 | click | linkText=Agenda CulturArte | 
    driver.findElement(By.linkText("Agenda CulturArte")).click();
  }
}
