// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CTTesteLoginRegularTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cTTesteLoginRegular() {
    // Test name: CT_TesteLoginRegular
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.get("http://localhost:5173/login");
    // 2 | setWindowSize | 1614x881 | 
    driver.manage().window().setSize(new Dimension(1614, 881));
    // 3 | click | id=:r1: | 
    driver.findElement(By.id(":r1:")).click();
    // 4 | type | id=:r1: | regular@user
    driver.findElement(By.id(":r1:")).sendKeys("regular@user");
    // 5 | click | id=:r3: | 
    driver.findElement(By.id(":r3:")).click();
    // 6 | type | id=:r3: | 123
    driver.findElement(By.id(":r3:")).sendKeys("123");
    // 7 | click | css=.MuiButtonBase-root | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    // 8 | mouseDownAt | css=.css-5pmatr | 366.0104179382324,19.028656005859375
    {
      WebElement element = driver.findElement(By.cssSelector(".css-5pmatr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 9 | mouseMoveAt | css=.css-5pmatr | 366.0104179382324,19.028656005859375
    {
      WebElement element = driver.findElement(By.cssSelector(".css-5pmatr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseUpAt | css=.css-5pmatr | 366.0104179382324,19.028656005859375
    {
      WebElement element = driver.findElement(By.cssSelector(".css-5pmatr"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 11 | click | css=.MuiButton-root | 
    driver.findElement(By.cssSelector(".MuiButton-root")).click();
  }
}
